/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground":
          "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        accent: "hsl(var(--accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground":
          "hsl(var(--destructive-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
      },
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        ":root": {
          "--background": "0 0% 96%",
          "--foreground": "222.2 84% 4.9%",
          "--card": "0 0% 100%",
          "--card-foreground": "222.2 84% 4.9%",
          "--popover": "0 0% 100%",
          "--popover-foreground": "222.2 84% 4.9%",
          "--primary": "338 78% 75%",
          "--primary-foreground": "210 40% 98%",
          "--secondary": "210 16% 90%",
          "--secondary-foreground": "222.2 47.4% 11.2%",
          "--muted": "210 40% 96.1%",
          "--muted-foreground": "215.4 16.3% 46.9%",
          "--accent": "152 78% 46%",
          "--accent-foreground": "210 40% 98%",
          "--destructive": "0 84.2% 60.2%",
          "--destructive-foreground": "210 40% 98%",
          "--border": "210 16% 90%",
          "--input": "0 0% 100%",
          "--ring": "152 78% 46%",
          "--radius": "0.5rem",
        },
        ".dark": {
          "--background": "0 0% 0%",
          "--foreground": "210 40% 98%",
          "--card": "0 0% 11%",
          "--card-foreground": "210 40% 98%",
          "--popover": "210 28% 9%",
          "--popover-foreground": "210 40% 98%",
          "--primary": "160 60% 45%",
          "--primary-foreground": "222.2 47.4% 11.2%",
          "--secondary": "215 16% 18%",
          "--secondary-foreground": "210 40% 98%",
          "--muted": "217 32% 16%",
          "--muted-foreground": "215.4 16.3% 46.9%",
          "--accent": "160 60% 45%",
          "--accent-foreground": "210 40% 98%",
          "--destructive": "0 62.8% 30.6%",
          "--destructive-foreground": "210 40% 98%",
          "--border": "0 0% 23%",
          "--input": "0 0% 17%",
          "--ring": "160 60% 45%",
          "--radius": "0.5rem",
        },
      });
    },
  ],
};
